<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
        <PackageReference Include="Dragablz" Version="0.0.3.234" />
        <PackageReference Include="MaterialDesignColors" Version="5.2.1" />
        <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.7">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.7" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.7" />
        <PackageReference Include="MvvmLightLibsStd10" Version="5.4.1.1" />
        <PackageReference Include="MySql.Data" Version="9.4.0" />
        <PackageReference Include="Serilog" Version="4.3.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="SimpleInjector" Version="5.5.0" />
        <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="Views\MainWindowView.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
      <None Remove="Images\ApexAuto(Main).jpg" />
      <None Update="appsettings.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Images\AutoApex(Main).jpg" />
      <None Remove="Images\ApexAuto(Icon).jpg" />
      <None Remove="Images\ApexAuto(Icon).ico" />
      <Resource Include="Images\ApexAuto(Icon).ico">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <None Remove="Images\ApexAuto(Main).ico" />
      <None Remove="Images\ApexAuto(MainBackGround).jpg" />
      <None Remove="Images\ApexAuto(Main_Logo).png" />
      <Resource Include="Images\ApexAuto(Main_Logo).png">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
      <None Remove="Logs.txt" />
      <Resource Include="Logs.txt">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Resource>
    </ItemGroup>
</Project>
